### ISSUE TITLE
Grant write access

### ISSUE THREAD

**Issue by draeger** [TakahiroYamada/SBMLWebApp#11]
Please add me to the list of contributors with write access to this project. Thanks.

**Comment by TakahiroYamada** [comment]
@draeger 
Hi. I sent you an invitation to this repo again,
Could you please check whether you receive it and get write  access?

With best regards.

Takahiro

**Comment by TakahiroYamada** [comment]
@draeger 

Hi. Could you get the invitation of access rights to this repo from GitHub??

Best. 

Takahiro

**Comment by draeger** [comment]
Nothing... I really can't see it

**Comment by TakahiroYamada** [comment]
Oh, maybe my way to add it could be falsch.

In `Setting` in the page of this repo, I selected `Manage access` menu and pushed the button of `invite a collaborator`, type `draeger` and selected your account.
Then you are listed as the potential collaborator with the text of "Awaiting draeger’s response" (Matthias and Kaito are also listed with the text of "Collaborator").

Could this way be falsch to add access right to you?

Sorry for your inconvenience...
Best.

Takahiro

**Comment by draeger** [comment]
That seems right. I just tried to invite @funasoul to SBSCL in the same way to test if it works for him. There you have a little clipboard symbol that you can click next to my name. Could you possibly send me this link via e-mail directly?

**Comment by TakahiroYamada** [comment]
Sounds Great!
OK, I will immediately do this and send it to you via e-mail!
Just a moment!

Takahiro

**Comment by TakahiroYamada** [comment]
I sent you an e-mail with the link embedded in clipboard!
Best

Takahiro

**Comment by draeger** [comment]
@TakahiroYamada Did you send it to andreas.draeger@uni-tuebingen.de? That would be correct. Nothing received yet.

**Comment by TakahiroYamada** [comment]
Oh, Sorry! I sent the e-mail to draeger@informatik.uni-tuebingen.de.
I will sent it to andreas.draeger@uni-tuebingen.de!

Sorry!!

Takahiro

**Comment by draeger** [comment]
Horray - it worked! 🎉🤩 But the other e-mail address is also correct.

**Comment by funasoul** [comment]
Andreas,

Thanks it worked :-)
-- 
Akira
