### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by matthiaskoenig** [TakahiroYamada/SBMLWebApp#3]
Can we rename the repository to `sbmlwebapp` or something similar short instead of 
`GSOC2017_SBMLModelAnalysisWebApp`? 
For the publication this should be more generic then a GSOC project. Also this will make all the names better.

**Comment by draeger** [comment]
I just notice this issue alread existed. I support this one and will merge #5 with this one.

**Comment by draeger** [comment]
I suggest using the name `SBMLWebApp`.

**Comment by TakahiroYamada** [comment]
@matthiaskoenig @draeger 

Thanks for your point!
I changed name of repo to `SBMLWebApp`.

Best.

Takahiro
